name: Nightly Jobs
permissions:
  contents: read

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  live-repo-smoke:
    uses: ./.github/workflows/live-repo-smoke-pr.yaml
  unit-and-smoke-tests:
    uses: ./.github/workflows/python-unit-tests.yaml
