name: Run Tests on Repositories

on:
  workflow_dispatch:

  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - ".github/workflows/python-tests.yaml"

permissions:
  contents: read

jobs:
  tests-genai-repo:
    name: Python Tests on generative-ai-for-beginners
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      id: python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -e .

    - name: Clone Repo
      run: git clone https://github.com/microsoft/generative-ai-for-beginners

    - name: Test Check Broken Paths in generative-ai-for-beginners
      if: always()
      run: |
        cd generative-ai-for-beginners
        markdown-checker -d . -f check_broken_paths -gu ''
    - name: Test Check URLs Country locale in generative-ai-for-beginners
      if: always()
      run: |
        cd generative-ai-for-beginners
        markdown-checker -d . -f check_urls_locale -gu ''
    - name: Test Check Broken URLs in generative-ai-for-beginners
      if: always()
      run: |
        cd generative-ai-for-beginners
        markdown-checker -d . -f check_broken_urls -gu ''

  tests-openai-repo:
    name: Python Tests on azure-search-openai-demo
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      id: python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -e .

    - name: Clone Repo
      run: git clone https://github.com/Azure-Samples/azure-search-openai-demo

    - name: Test Check Broken Paths in azure-search-openai-demo
      if: always()
      run: |
        cd azure-search-openai-demo
        markdown-checker -d . -f check_broken_paths -gu ''
    - name: Test Check URLs Country locale in azure-search-openai-demo
      if: always()
      run: |
        cd azure-search-openai-demo
        markdown-checker -d . -f check_urls_locale -gu ''
 
    - name: Test Check Broken URLs in azure-search-openai-demo
      if: always()
      run: |
        cd azure-search-openai-demo
        markdown-checker -d . -f check_broken_urls -gu ''
 
  tests-phicookbook-repo:
    name: Python Tests on Phi-3CookBook
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      id: python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -e .

    - name: Clone Repo
      run: git clone https://github.com/microsoft/Phi-3CookBook

    - name: Test Check Broken Paths in Phi-3CookBook
      if: always()
      run: |
        cd Phi-3CookBook
        markdown-checker -d . -f check_broken_paths -gu ''
    - name: Test Check URLs Country locale in Phi-3CookBook
      if: always()
      run: |
        cd Phi-3CookBook
        markdown-checker -d . -f check_urls_locale -gu ''
    - name: Test Check Broken URLs in Phi-3CookBook
      if: always()
      run: |
        cd Phi-3CookBook
        markdown-checker -d . -f check_broken_urls -gu ''
