name: Run Python type, lint and format checks

on:
  workflow_dispatch:
  push:
    branches: [ main, dev ]
    paths:
      - '**.py'
      - ".github/workflows/python-types-lint-format.yaml"

  pull_request:
    branches: [ main, dev ]
    paths:
      - '**.py'
      - ".github/workflows/python-types-lint-format.yaml"

permissions:
  contents: read

jobs:
  python-type-check:
    if: ${{ always() }} # Always run even if a matrix candidate fails
    name: Python ${{ matrix.python_version }} - Check Type - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python_version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v6
    - uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: uv sync --extra dev

    - name: Run type check
      run: uv run mypy .

  python-lint-format-check:
    if: ${{ always() }} # Always run even if a matrix candidate fails
    name: Python ${{ matrix.python_version }} - Check Linting and Formatting - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python_version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v6
    - uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: uv sync --extra lint

    - name: Run lint check
      run: uv run ruff check .

    - name: Run format check
      run: uv run ruff format . --check
