name: Release to Pypi

on:
  release:
    types:
      - published
  workflow_dispatch:

env:
  DEFAULT_PYTHON: '3.10'

permissions:
  contents: read
jobs:
  release-pypi:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from Github
        uses: actions/checkout@v6
      - name: Set up uv
        id: python
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Build distributions
        run: uv build
      - name: Upload to PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: uv publish
